package com.yihukurama.lcontroler.model.access.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOVE_MEMORY.
 */
public class LoveMemory {

    /** Not-null value. */
    private String id;
    private String description;
    private String message;
    private String birthyear;
    private String birthmonth;
    private String birthday;

    public LoveMemory() {
    }

    public LoveMemory(String id) {
        this.id = id;
    }

    public LoveMemory(String id, String description, String message, String birthyear, String birthmonth, String birthday) {
        this.id = id;
        this.description = description;
        this.message = message;
        this.birthyear = birthyear;
        this.birthmonth = birthmonth;
        this.birthday = birthday;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getBirthyear() {
        return birthyear;
    }

    public void setBirthyear(String birthyear) {
        this.birthyear = birthyear;
    }

    public String getBirthmonth() {
        return birthmonth;
    }

    public void setBirthmonth(String birthmonth) {
        this.birthmonth = birthmonth;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

}
