package com.yihukurama.lcontroler.model.access.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    /** Not-null value. */
    private String userid;
    private String account;
    private String nickname;
    private String headurl;
    private String birthyear;
    private String birthmonth;
    private String birthday;
    private String birthhour;
    private String birthmin;
    private String birthsec;
    private String heigh;
    private String weight;
    private String chest;
    private String waistline;
    private String hipline;
    private String clothessize;
    private String shoessize;
    private String trouserssize;
    private String interests;

    public User() {
    }

    public User(String userid) {
        this.userid = userid;
    }

    public User(String userid, String account, String nickname, String headurl, String birthyear, String birthmonth, String birthday, String birthhour, String birthmin, String birthsec, String heigh, String weight, String chest, String waistline, String hipline, String clothessize, String shoessize, String trouserssize, String interests) {
        this.userid = userid;
        this.account = account;
        this.nickname = nickname;
        this.headurl = headurl;
        this.birthyear = birthyear;
        this.birthmonth = birthmonth;
        this.birthday = birthday;
        this.birthhour = birthhour;
        this.birthmin = birthmin;
        this.birthsec = birthsec;
        this.heigh = heigh;
        this.weight = weight;
        this.chest = chest;
        this.waistline = waistline;
        this.hipline = hipline;
        this.clothessize = clothessize;
        this.shoessize = shoessize;
        this.trouserssize = trouserssize;
        this.interests = interests;
    }

    /** Not-null value. */
    public String getUserid() {
        return userid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getHeadurl() {
        return headurl;
    }

    public void setHeadurl(String headurl) {
        this.headurl = headurl;
    }

    public String getBirthyear() {
        return birthyear;
    }

    public void setBirthyear(String birthyear) {
        this.birthyear = birthyear;
    }

    public String getBirthmonth() {
        return birthmonth;
    }

    public void setBirthmonth(String birthmonth) {
        this.birthmonth = birthmonth;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getBirthhour() {
        return birthhour;
    }

    public void setBirthhour(String birthhour) {
        this.birthhour = birthhour;
    }

    public String getBirthmin() {
        return birthmin;
    }

    public void setBirthmin(String birthmin) {
        this.birthmin = birthmin;
    }

    public String getBirthsec() {
        return birthsec;
    }

    public void setBirthsec(String birthsec) {
        this.birthsec = birthsec;
    }

    public String getHeigh() {
        return heigh;
    }

    public void setHeigh(String heigh) {
        this.heigh = heigh;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getChest() {
        return chest;
    }

    public void setChest(String chest) {
        this.chest = chest;
    }

    public String getWaistline() {
        return waistline;
    }

    public void setWaistline(String waistline) {
        this.waistline = waistline;
    }

    public String getHipline() {
        return hipline;
    }

    public void setHipline(String hipline) {
        this.hipline = hipline;
    }

    public String getClothessize() {
        return clothessize;
    }

    public void setClothessize(String clothessize) {
        this.clothessize = clothessize;
    }

    public String getShoessize() {
        return shoessize;
    }

    public void setShoessize(String shoessize) {
        this.shoessize = shoessize;
    }

    public String getTrouserssize() {
        return trouserssize;
    }

    public void setTrouserssize(String trouserssize) {
        this.trouserssize = trouserssize;
    }

    public String getInterests() {
        return interests;
    }

    public void setInterests(String interests) {
        this.interests = interests;
    }

}
